### ISSUE TITLE
BQ does not allow dataset name (schema) in WHERE condition

### ISSUE THREAD

**Issue by jdposada** [ohdsi-studies/PCE#3]
Hi @jreps,

Sorry I should have caught this in the prior issue

https://github.com/ohdsi-studies/PCE/blob/379ff7dedad4fac0accae5560734891c4094c8bd/R/MeasurementCohortCovariateCode.R#L57

**Comment by ChenyuL** [comment]
@jreps  I used left join instead of where condition in this sql. But I'm not able to test this on my one device.  I'm trying figure out how to run the test right now


# Some SQL to construct the covariate:
  sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
      "{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
      "{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
  "measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time, value_as_number raw_value",
  "from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
   and measurement_date >= dateadd(day, @startDay, cohort_start_date) and 
   measurement_date <= dateadd(day, @endDay, cohort_start_date)",
  "{@ageInteraction | @lnAgeInteraction}?{inner join @cdm_database_schema.person p on p.person_id=c.subject_id}",
 "WHERE @type IN (",
       "SELECT @type from @cohort_temp_table LEFT JOIN  @cohort_database_schema.@cohort_table ON  @cohort_database_schema.@cohort_table.subject_id = @cohort_temp_table.subject_id",
   "AND @cohort_database_schema.@cohort_table.cohort_definition_id = @cohort_id",
   "AND @cohort_database_schema.@cohort_table.cohort_start_date <= dateadd(day, @endDay, c.cohort_start_date)",
   "AND @cohort_database_schema.@cohort_table.cohort_end_date >= dateadd(day, @startDay, c.cohort_start_date)",
      ")",
  "AND m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }"
  )

**Comment by ChenyuL** [comment]
I used left join instead of where condition in this sql. But I'm not able to test this on my one device. I'm trying figure out how to run the test right now

#Some SQL to construct the covariate:
  sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
      "{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
      "{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
  "measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time, value_as_number raw_value",
  "from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
   and measurement_date >= dateadd(day, @startDay, cohort_start_date) and 
   measurement_date <= dateadd(day, @endDay, cohort_start_date)",
  "{@ageInteraction | @lnAgeInteraction}?{inner join @cdm_database_schema.person p on p.person_id=c.subject_id}",
 "WHERE @type IN (",
       "SELECT @type from @cohort_temp_table LEFT JOIN  @cohort_database_schema.@cohort_table ON @cohort_database_schema.@cohort_table.subject_id = @cohort_temp_table.subject_id",
   "AND @cohort_database_schema.@cohort_table.cohort_definition_id = @cohort_id",
   "AND @cohort_database_schema.@cohort_table.cohort_start_date <= dateadd(day, @endDay, c.cohort_start_date)",
   "AND @cohort_database_schema.@cohort_table.cohort_end_date >= dateadd(day, @startDay, c.cohort_start_date)",
      ")",
  "AND m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }"
  )

**Comment by ChenyuL** [comment]
I used left join instead of where condition in this sql. But I'm not able to test this on my one device. I'm trying figure out how to run the test right now
```{r}
#Some SQL to construct the covariate:
  sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
      "{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
      "{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
  "measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time, value_as_number raw_value",
  "from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
   and measurement_date >= dateadd(day, @startDay, cohort_start_date) and 
   measurement_date <= dateadd(day, @endDay, cohort_start_date)",
  "{@ageInteraction | @lnAgeInteraction}?{inner join @cdm_database_schema.person p on p.person_id=c.subject_id}",
 "WHERE @type IN (",
       "SELECT @type from @cohort_temp_table LEFT JOIN  @cohort_database_schema.@cohort_table ON @cohort_database_schema.@cohort_table.subject_id = @cohort_temp_table.subject_id",
   "AND @cohort_database_schema.@cohort_table.cohort_definition_id = @cohort_id",
   "AND @cohort_database_schema.@cohort_table.cohort_start_date <= dateadd(day, @endDay, c.cohort_start_date)",
   "AND @cohort_database_schema.@cohort_table.cohort_end_date >= dateadd(day, @startDay, c.cohort_start_date)",
      ")",
  "AND m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }"
  )
```

**Comment by jdposada** [comment]
hi @ChenyuL ,

Thank you for modifying this. The statement below will still cause issues

AND @cohort_database_schema.@cohort_table

In BigQuery The database schema cannot be part of a where condition. Will the query work if we remove @cohort_database_schema from all those WHERE clauses?

@jreps

**Comment by jreps** [comment]
I think something like this might work:

sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
             "{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
             "{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
             "measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time, value_as_number raw_value",
             "from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
             and measurement_date >= dateadd(day, @startDay, cohort_start_date) and 
             measurement_date <= dateadd(day, @endDay, cohort_start_date)",
             "{@ageInteraction | @lnAgeInteraction}?{inner join @cdm_database_schema.person p on p.person_id=c.subject_id}",
             "LEFT JOIN (",
             "SELECT distinct subject_id from @cohort_temp_table c2 inner join",
             "@cohort_database_schema.@cohort_table inc_cohort on c2.subject_id = inc_cohort.subject_id",
             "where inc_cohort.cohort_definition_id = @cohort_id",
             "AND inc_cohort.cohort_start_date <= dateadd(day, @endDay, c2.cohort_start_date)",
             "AND inc_cohort.cohort_end_date >= dateadd(day, @startDay, c2.cohort_start_date)",
             ") inc on c.subject_id = inc.subject_id",
             "WHERE m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }",
             " AND inc.subject_id is @type NULL"
)

**Comment by jdposada** [comment]
hi @jreps ,

Looks like your solution did work. I will close this issue when I confirm everything is ok.

Thanks a lot

**Comment by jdposada** [comment]
Hi @jreps 

Solution worked! We are looking at the results verifying everything is fine. I tweaked the final SQL slightly. The final version is below

For **MeasurementCovariateCode.R**
```R
  sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
      "{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
      "{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
  "measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time,value_as_number raw_value, YEAR(c.cohort_start_date)-p.year_of_birth as age",
  "from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
   and measurement_date >= dateadd(day, @startDay, cohort_start_date) and 
   measurement_date <= dateadd(day, @endDay, cohort_start_date)",
  "inner join @cdm_database_schema.person p on p.person_id=c.subject_id",
  "where m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }"
  )
```

For **MeasurementCohortCovariate.R**

```R
sql <- paste("select c.@row_id_field AS row_id, measurement_concept_id, unit_concept_id,",
"{@lnAgeInteraction}?{LOG(YEAR(c.cohort_start_date)-p.year_of_birth)*}:{{@ageInteraction}?{(YEAR(c.cohort_start_date)-p.year_of_birth)*}}",
"{@lnValue}?{LOG(value_as_number)}:{value_as_number} as value_as_number,",
"measurement_date, abs(datediff(dd, measurement_date, c.cohort_start_date)) as index_time, value_as_number raw_value",
"from @cdm_database_schema.measurement m inner join @cohort_temp_table c on c.subject_id = m.person_id
and measurement_date >= dateadd(day, @startDay, cohort_start_date) and
measurement_date <= dateadd(day, @endDay, cohort_start_date)",
"{@ageInteraction | @lnAgeInteraction}?{inner join @cdm_database_schema.person p on p.person_id=c.subject_id}",
"LEFT JOIN (",
"SELECT distinct c2.subject_id from @cohort_temp_table c2 inner join",
"@cohort_database_schema.@cohort_table inc_cohort on c2.subject_id = inc_cohort.subject_id",
"where inc_cohort.cohort_definition_id = @cohort_id",
"AND inc_cohort.cohort_start_date <= dateadd(day, @endDay, c2.cohort_start_date)",
"AND inc_cohort.cohort_end_date >= dateadd(day, @startDay, c2.cohort_start_date)",
") inc on c.subject_id = inc.subject_id",
"WHERE m.measurement_concept_id in (@concepts) {@lnValue}?{ and value_as_number >0 }",
" AND inc.subject_id is @type NULL"
)
```
